//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSalutemSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClinicUsers()
        {
            this.Patients = new HashSet<Patients>();
            this.Patients1 = new HashSet<Patients>();
        }
    
        public int IdUser { get; set; }
        public string UserName { get; set; }
        public string UserSurname { get; set; }
        public string UserPesel { get; set; }
        public string UserSex { get; set; }
        public string UserProfession { get; set; }
        public string UserSpecialization { get; set; }
        public string UserLogin { get; set; }
        public string UserPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patients> Patients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Patients> Patients1 { get; set; }
    }
}
