//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicSalutemSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients
    {
        public int ID { get; set; }
        public string PatientName { get; set; }
        public string PatientSurname { get; set; }
        public string PatientPesel { get; set; }
        public int IdUserDoctor { get; set; }
        public int IdUserNurse { get; set; }
        public System.DateTime PatientVisitDay { get; set; }
        public Nullable<System.TimeSpan> PatientVisitTime { get; set; }
    
        public virtual ClinicUsers ClinicUsers { get; set; }
        public virtual ClinicUsers ClinicUsers1 { get; set; }
    }
}
